[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://campus-connect-six.vercel.app/"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
  signed = "API_SIGNATURE_TOKEN"